services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: trp_data_dashboard
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: "pip install -r requirements.txt"
    # A src/[app_name].py file must exist and contain `server=app.server`
    startCommand: "gunicorn --log-level=DEBUG --chdir src data_dashboard:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # https://community.render.com/t/timeout-when-preloading-pytorch-model-using-flask-on-render-com/1318/4
      # render secretly adds a --preload flag, we explicitly remove it here
      - key: GUNICORN_CMD_ARGS
        value: --access-logfile - --bind=0.0.0.0:10000
        